### ISSUE TITLE
reclass on https://pypi.python.org/

### ISSUE THREAD

**Issue by shomodj** [madduck/reclass#23]
Why not add reclass to pypi so that pip can be used to install it?

**Comment by tomkukral** [comment]
Hi, I'd love to have reclass available on pypi (for installing using `pip`). 

I've already tried to upload it to testing pypi - https://testpypi.python.org/pypi/reclass 
I can upload the package to production pypi as well if @madduck is fine with it.

I'm not a Python specialist but I'll try to make my best.

**Comment by Rtzq0** [comment]
The githubian way to do this is probably with travis-ci.org and https://docs.travis-ci.com/user/deployment/pypi/

**Comment by tomkukral** [comment]
I agree that build pipeline would be the best options. However latest release is more than 2 years old and thus manual releasing could be sufficient, IMHO.

What about relasing manually now and estabilish build pipeline by the time there will be something new to release?

**Comment by lottspot** [comment]
Travis does seem like a natural choice, we'll just have to work out the details of the pipeline configuration.

I do agree though that preparing a manual package upload would be sufficient for now, since we really only need the pipeline in place by *the next time* we prepare a release. Getting reclass on pypi seems like an easy win for us that makes a lot of people's lives a lot easier. I can look into taking care of this in the near future.

**Comment by Rtzq0** [comment]
Have spoken with @lottspot , will take ownership and get done before 2017 hopefully.

**Comment by tomkukral** [comment]
Great, you can take an inspiration in https://github.com/tomkukral/reclass/blob/travis/.travis.yml

**Comment by Rtzq0** [comment]
@tomkukral you are now officially the blocker since you've registered reclass on testpypi.python.org. Please transfer ownership over to rtzq0 so that I can validate the manifest and close out this bug for you :-)

**Comment by tomkukral** [comment]
@Rtzq0 done, you are now the owner of reclass on test pypi

**Comment by Rtzq0** [comment]
Alright, I've opened a separate issue for travis-ci tracking and discussion since the root cause of this guy is closed out.
