### ISSUE TITLE
New fork-- Does upstream want merges?

### ISSUE THREAD

**Issue by ub1quit33** [madduck/reclass#54]
Hello! I've noticed that development on the main repository seems to have gone stale, with the last commit being a couple of years ago. Since then, some great work has been done on Reclass in separate branches.

Today, I started my own fork in which I am attempting to consolidate a lot of that disparate work under a single branch, and have plans to add new work of my own to the project.

My question is: Is upstream interested in any of this work being merged back, or would you prefer that I continue this work as an independent fork?

**Comment by madduck** [comment]
Hey,

I am fully aware I've been neglecting reclass due to various reasons. I am very excited to see you wanting to take this on.

Part of the reason I've not tocuhed reclass is that it simply works for me and does almost everything I need. But yes, I know that I've been irresponsible at managing this project.

I'll be keen to see your work and would gladly merge it in, if it works like the current version and integrates the good work on other branches.

Thanks!
-martin

**Comment by ub1quit33** [comment]
Sounds good! I certainly wouldn't use any words as heavy as "irresponsible", as managing a project certainly takes a lot of time. I have a couple of planned additions I would like to make in time, and a couple of things which I noticed may need to be better assimilated from the work which was merged in.

I must say though as I've dove into the code, I think this is a great project, and it's clealy very well written. Thanks for all of your hard work on this awesome application!

Merge requests coming in th future...
